import * as THREE from 'three';
import {createArmoredKart} from './armored-kart.js';
try{
const canvas=document.querySelector('#view'),host=canvas.parentElement;
const renderer=new THREE.WebGLRenderer({canvas,antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,1.7));renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;
const scene=new THREE.Scene();scene.background=new THREE.Color(0x1b2b32);scene.fog=new THREE.Fog(0x1b2b32,80,140);
const camera=new THREE.PerspectiveCamera(37,1,.1,200);scene.add(new THREE.HemisphereLight(0xe0faff,0x4b5459,2));
for(const [color,intensity,position] of [[0xffe4c5,3.5,[20,35,25]],[0x68d7eb,3,[-22,15,-20]],[0xffffff,2,[-15,18,25]]]){const light=new THREE.DirectionalLight(color,intensity);light.position.set(...position);scene.add(light);if(color===0xffe4c5){light.castShadow=true;light.shadow.mapSize.set(2048,2048);Object.assign(light.shadow.camera,{left:-20,right:20,top:20,bottom:-20,near:1,far:90});light.shadow.normalBias=.025;}}
const envScene=new THREE.Scene();envScene.background=new THREE.Color(0x758b92);
for(const [x,y,z,w,h] of [[-15,10,8,7,20],[15,12,-10,8,22],[0,25,0,20,10]]){const m=new THREE.Mesh(new THREE.PlaneGeometry(w,h),new THREE.MeshBasicMaterial({color:0xffffff}));m.position.set(x,y,z);m.lookAt(0,2,0);envScene.add(m);}const pmrem=new THREE.PMREMGenerator(renderer),environment=pmrem.fromScene(envScene,.02);scene.environment=environment.texture;pmrem.dispose();envScene.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});
const car=createArmoredKart();car.getObjectByName('Race driver').visible=false;scene.add(car);
const floor=new THREE.Mesh(new THREE.PlaneGeometry(180,180),new THREE.MeshStandardMaterial({color:0x1c2c32,roughness:.7,metalness:.18}));floor.rotation.x=-Math.PI/2;floor.position.y=-3.85;floor.receiveShadow=true;scene.add(floor);
const podium=new THREE.Mesh(new THREE.CylinderGeometry(15,15.3,.35,96),new THREE.MeshStandardMaterial({color:0x283c43,metalness:.35,roughness:.5}));podium.position.y=-3.67;podium.receiveShadow=true;scene.add(podium);
let yaw=.65,pitch=.36,distance=43,dragging=false,px=0,py=0,last=performance.now();const target=new THREE.Vector3(0,1.8,0);
const rotate=document.querySelector('#rotate');if(matchMedia('(prefers-reduced-motion: reduce)').matches)rotate.checked=false;
function frame(now){requestAnimationFrame(frame);const dt=Math.min((now-last)/1000,.05);last=now;if(document.hidden)return;if(rotate.checked&&!dragging)yaw+=dt*.16;
 camera.position.set(Math.sin(yaw)*Math.cos(pitch)*distance,Math.sin(pitch)*distance,Math.cos(yaw)*Math.cos(pitch)*distance).add(target);camera.lookAt(target);renderer.render(scene,camera);}
canvas.addEventListener('pointerdown',e=>{dragging=true;px=e.clientX;py=e.clientY;canvas.setPointerCapture(e.pointerId);rotate.checked=false;});canvas.addEventListener('pointermove',e=>{if(!dragging)return;yaw-=(e.clientX-px)*.008;pitch=THREE.MathUtils.clamp(pitch+(e.clientY-py)*.005,-.06,1.45);px=e.clientX;py=e.clientY;});for(const name of ['pointerup','pointercancel'])canvas.addEventListener(name,()=>dragging=false);
canvas.addEventListener('wheel',e=>{e.preventDefault();distance=THREE.MathUtils.clamp(distance+e.deltaY*.035,24,70);},{passive:false});canvas.addEventListener('keydown',e=>{if(!e.key.startsWith('Arrow'))return;e.preventDefault();rotate.checked=false;if(e.key==='ArrowLeft')yaw-=.15;if(e.key==='ArrowRight')yaw+=.15;if(e.key==='ArrowUp')pitch=Math.min(1.45,pitch+.12);if(e.key==='ArrowDown')pitch=Math.max(-.06,pitch-.12);});
const views={hero:[.65,.36],front:[0,.18],rear:[Math.PI,.25],side:[Math.PI/2,.18],top:[0,1.45]};document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{[yaw,pitch]=views[b.dataset.view];rotate.checked=false;document.querySelectorAll('[data-view]').forEach(x=>x.classList.toggle('active',x===b));}));
document.querySelector('#driver').addEventListener('change',e=>car.getObjectByName('Race driver').visible=e.target.checked);document.querySelector('#wireframe').addEventListener('change',e=>car.traverse(o=>{if(o.isMesh&&o.material)o.material.wireframe=e.target.checked;}));
document.querySelectorAll('[data-color]').forEach(b=>b.addEventListener('click',()=>{car.traverse(o=>{if(o.material?.isMeshPhysicalMaterial&&o.material.clearcoat===1&&o.material.roughness===.27)o.material.color.setHex(parseInt(b.dataset.color,16));});document.querySelectorAll('[data-color]').forEach(x=>x.classList.toggle('active',x===b));}));
function resize(){const {width,height}=host.getBoundingClientRect();renderer.setSize(width,height,false);camera.aspect=width/height;camera.updateProjectionMatrix();distance=Math.max(43,15/Math.sin(Math.atan(Math.tan(37*Math.PI/360)*camera.aspect)));}new ResizeObserver(resize).observe(host);resize();requestAnimationFrame(frame);
}catch(error){document.querySelector('#error').hidden=false;console.error(error);}
