const VERSION = "e055be7ec938ebb1";
const SHELL = ["assets/TitanModel-BZQASsjr.js","assets/fonts/barlow-medium.ttf","assets/fonts/barlow-regular.ttf","assets/fonts/barlow-semibold.ttf","assets/fonts/cormorant-italic.ttf","assets/fonts/cormorant.ttf","assets/frameTime-Cdh5MlCm.js","assets/game-BrhfBrrL.css","assets/game-DlSeIJHS.js","assets/grapple-9twdRqAa.js","assets/grapple-CC54MCtk.css","assets/models-Cwm-pGHJ.js","assets/rapier-CKC5f6tm.js","assets/three-CUlnwgna.js","grapple.html","index.html","model-preview.html"];
/* VERSION and SHELL are generated by the Vite build. No CDN or runtime library. */
const PREFIX = 'wings-flight-';
const CACHE = PREFIX + VERSION;
const base = self.registration.scope;
const downloads = new Map();
self.addEventListener('install', () => self.skipWaiting());
self.addEventListener('activate', event => event.waitUntil((async () => {
  await self.clients.claim();
  for (const name of await caches.keys()) if (name.startsWith(PREFIX) && name !== CACHE) await caches.delete(name);
})()));

async function byteRange(response, header) {
  const match = /^bytes=(\d*)-(\d*)$/.exec(header);
  if (!match || (!match[1] && !match[2])) return response;
  const blob = await response.blob(), size = blob.size;
  const start = match[1] ? Number(match[1]) : Math.max(0, size - Number(match[2]));
  const end = match[1] && match[2] ? Math.min(size - 1, Number(match[2])) : size - 1;
  if (start >= size || start > end) return new Response(null, { status: 416, headers: { 'Content-Range': `bytes */${size}` } });
  return new Response(blob.slice(start, end + 1), { status: 206, headers: {
    'Content-Type': response.headers.get('Content-Type') || 'audio/mp4', 'Accept-Ranges': 'bytes',
    'Content-Range': `bytes ${start}-${end}/${size}`, 'Content-Length': String(end - start + 1),
  } });
}

async function asset(request, event) {
  const cache = await caches.open(CACHE).catch(() => null), url = request.url;
  if (!cache) return fetch(request);
  const cached = await cache.match(url);
  if (cached) return request.headers.has('Range') ? byteRange(cached, request.headers.get('Range')) : cached;
  // Fetch once and cache compressed bytes. Media requests must receive valid
  // byte ranges even on the first download, or the initial 0:20 seek can abort.
  if (!downloads.has(url)) {
    const headers = new Headers(request.headers); headers.delete('Range');
    const download = fetch(new Request(request, { headers })).then(response => {
      const save = (response.ok && response.status === 200 ? cache.put(url, response.clone()) : Promise.resolve()).catch(() => {});
      event.waitUntil(save.finally(() => downloads.delete(url)));
      return response;
    }).catch(error => { downloads.delete(url); throw error; });
    downloads.set(url, download);
  }
  const response = (await downloads.get(url)).clone();
  return request.headers.has('Range') && response.ok ? byteRange(response, request.headers.get('Range')) : response;
}

self.addEventListener('fetch', event => {
  const request = event.request, url = new URL(request.url);
  if (request.method !== 'GET' || !request.url.startsWith(base) || url.origin !== self.location.origin) return;
  if (request.mode === 'navigate') {
    event.respondWith((async () => {
      const cache = await caches.open(CACHE).catch(() => null);
      if (!cache) return fetch(request);
      const cached = await cache.match(request) || await cache.match(new URL('index.html', base));
      try {
        const response = await fetch(request, cached ? { signal: AbortSignal.timeout(2000) } : undefined);
        if (response.ok) event.waitUntil(cache.put(request, response.clone()).catch(() => {}));
        return response.ok || !cached ? response : cached;
      } catch { return cached || Response.error(); }
    })());
  } else if (/\.(js|css|glb|webp|m4a|ttf)$/.test(url.pathname)) event.respondWith(asset(request, event));
});

self.addEventListener('message', event => {
  if (event.data !== 'warm-shell') return;
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // Low concurrency keeps this optional work from saturating a weak connection.
    for (const file of SHELL) {
      const url = new URL(file, base).href;
      if (await cache.match(url)) continue;
      try { const response = await fetch(url); if (response.ok) await cache.put(url, response); } catch { /* Retry on the next visit. */ }
    }
  })());
});
